config/routes.rb
Rails.application.routes.draw do  
  root 'page#index'

  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  get "notifications" => "page#notifications"

  resources :posts, only: [:create, :show] do
    post "like", on: :member
    
    resources :comments, only: :create do
      member do
        post "comment"
        post "like"
      end
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include PublicActivity::Model
  include ActsAsCommentable::Comment
  
  acts_as_votable
  acts_as_commentable

  # default_scope -> { order('created_at ASC') }

  belongs_to :commentable, :polymorphic => true, :counter_cache => :comments_count
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  include PublicActivity::Model
  
  acts_as_votable
  acts_as_commentable
  
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_voter
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, :last_name, presence: true

  has_many :posts

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_notifications

  protected

  def set_notifications
    @notifications = PublicActivity::Activity.where(recipient_id: current_user.id).order(created_at: :desc) if user_signed_in?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :like, :comment]
  before_action :set_comment, only: [:show, :edit, :update, :destroy, :like]

  # GET /comments
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  def create
    post = Post.find params[:post_id]

    @comment = post.comments.create(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      post.create_activity key: 'post.comment', owner: current_user, recipient: post.user unless post.user == current_user

      flash[:success] = 'Comment was successfully created.'
      redirect_to post_url(post)
    else
      render :new
    end
  end

  # PATCH/PUT /comments/1
  def update
    if @comment.update(comment_params)
      redirect_to @comment, notice: 'Comment was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /comments/1
  def destroy
    @comment.destroy
    redirect_to comments_url, notice: 'Comment was successfully destroyed.'
  end

  def comment
    post = Post.find params[:post_id]
    comment = Comment.find params[:id]

    @comment = comment.comments.create(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      comment.create_activity key: 'comment.comment', owner: current_user, recipient: comment.user unless comment.user == current_user

      flash[:success] = 'Comment was successfully created.'
      redirect_to post_url(post)
    else
      flash[:danger] = 'Comment was failed to create.'
      redirect_to post_url(post)
    end
  end

  def like
    @post = Post.find params[:post_id]
    @comment.like_by current_user
    
    @comment.create_activity key: 'comment.like', owner: current_user, recipient: @comment.user unless @comment.user == current_user

    flash[:success] = 'Successfully like this post'
    redirect_to post_url(@post)
  end

  private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def comment_params
      params.require(:comment).permit(:comment)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  after_action :set_read_at, only: :notifications

  def index
    @post = Post.new
    @posts = Post.order(created_at: :desc).page(params[:page])
  end

  def notifications
  end

  private
  
    def set_read_at
      notifs = @notifications.where(read_at: nil)
      @notifications.where(read_at: nil).update_all(read_at: Time.now) unless notifs.empty?
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :like]
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like]

  # GET /posts
  def index
    @posts = Post.all
  end

  # GET /posts/1
  def show
    @comment = Comment.new
    @comments = @post.comments.order(created_at: :desc).page(params[:page])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      flash[:success] = 'Post was successfully created.'
      redirect_to root_url
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  def like
    @post.like_by current_user

    @post.create_activity key: 'post.like', owner: current_user, recipient: @post.user unless @post.user == current_user

    flash[:success] = 'Successfully like this post'
    redirect_to post_url(@post)
  end

  private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def post_params
      params.require(:post).permit(:user_id, :content)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  private

    def sign_up_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end

    def account_update_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def count_notifications(notifications)
    notifications.where(read_at: nil).count
  end

  def readed(read_at)
    'active' unless read_at
  end
end

app/views/comments/_form.html.slim
= simple_form_for(@comment) do |f|
  = f.error_notification

  .form-inputs
    = f.input :user_id
    = f.input :comment

  .form-actions
    = f.button :submit

app/views/comments/edit.html.slim
h1 Editing comment

== render 'form'

= link_to 'Show', @comment
'|
= link_to 'Back', comments_path

app/views/comments/index.html.slim
h1 Listing comments

table
  thead
    tr
      th User
      th Comment
      th
      th
      th

  tbody
    - @comments.each do |comment|
      tr
        td = comment.user_id
        td = comment.comment
        td = link_to 'Show', comment
        td = link_to 'Edit', edit_comment_path(comment)
        td = link_to 'Destroy', comment, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Comment', new_comment_path

app/views/comments/new.html.slim
h1 New comment

== render 'form'

= link_to 'Back', comments_path

app/views/comments/show.html.slim
p#notice = notice

p
  strong User:
  = @comment.user_id
p
  strong Comment:
  = @comment.comment

= link_to 'Edit', edit_comment_path(@comment)
'|
= link_to 'Back', comments_path

app/views/layouts/_flash.html.slim
- if flash
  - flash.each do |type, message|
    div class="alert alert-#{type} alert-dismissible" role="alert"
      button.close aria-label="Close" data-dismiss="alert" type="button" 
        span aria-hidden="true"  &times;
      
      = message

app/views/layouts/_menu.html.slim
= nav_bar brand: "socialAppks", responsive: true do
  - if user_signed_in?
    = menu_group do
      = menu_item "Home", root_path
      = menu_item notifications_path do
        | Notifications 
        span.badge= count_notifications(@notifications)
    = menu_group pull: :right do
      = drop_down "Account" do
        = menu_item "Log Out", destroy_user_session_path, method: :delete
  - else
    = menu_group do
      = menu_item "Home", root_path
    = menu_group pull: :right do
      = menu_item "Sign In", new_user_session_path
      = menu_item "Sign Up", new_user_registration_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title SocialAppks
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = render "layouts/menu"
    .container
      = render "layouts/flash"
      = yield

app/views/page/index.html.slim
- if user_signed_in?
  = simple_form_for @post do |f|
    .panel.panel-info
      .panel-heading New Status
      .panel-body
        = f.input :content, label: false, placeholder: 'Create status here...'
      .panel-footer
        = f.button :submit, "Submit", class: 'btn btn-primary'

- @posts.each do |post|
  .panel.panel-default
    .panel-body
      strong= "#{post.user.full_name} : "
      = post.content
    .panel-footer
      = link_to pluralize(post.cached_votes_total, 'like'), like_post_path(post), method: :post, class: 'btn btn-sm'
      = link_to pluralize(post.comments_count, 'comment'), post_path(post), class: 'btn btn-sm'
      .pull-right= post.created_at.strftime("%B %d, %Y at %H:%M")
      
= paginate @posts

app/views/page/notifications.html.slim
.col-md-8.col-md-offset-2
  .panel.panel-success
    .panel-heading Notifications
    .list-group
      - if @notifications.empty?
        a.list-group-item
          h4.list-group-item-heading You don't have any notifications.
      - else
        - @notifications.each do |notification|
          - case notification.key
          - when "post.comment"
            = link_to post_path(notification.trackable), class: "list-group-item #{readed(notification.read_at)}" do
              h4.list-group-item-heading
                i= notification.owner.full_name
                |  comment your post 
                = "\"#{strip_tags(truncate(notification.trackable.content, length: 50))}\""
              p.list-group-item-text
                small= notification.created_at.strftime("%B %d, %Y at %H:%M")
          - when "post.like"
            = link_to post_path(notification.trackable), class: "list-group-item #{readed(notification.read_at)}" do
              h4.list-group-item-heading
                i= notification.owner.full_name
                |  like your post 
                = "\"#{strip_tags(truncate(notification.trackable.content, length: 50))}\""
              p.list-group-item-text
                small= notification.created_at.strftime("%B %d, %Y at %H:%M")
          - when "comment.comment"
            = link_to post_path(notification.trackable.commentable), class: "list-group-item #{readed(notification.read_at)}" do
              h4.list-group-item-heading
                i= notification.owner.full_name
                |  reply your comment 
                = "\"#{strip_tags(truncate(notification.trackable.comment, length: 50))}\""
              p.list-group-item-text
                small= notification.created_at.strftime("%B %d, %Y at %H:%M")
          - when "comment.like"
            = link_to post_path(notification.trackable.commentable), class: "list-group-item #{readed(notification.read_at)}" do
              h4.list-group-item-heading
                i= notification.owner.full_name
                |  like your comment 
                = "\"#{strip_tags(truncate(notification.trackable.comment, length: 50))}\""
              p.list-group-item-text
                small= notification.created_at.strftime("%B %d, %Y at %H:%M")

app/views/posts/_form.html.slim
= simple_form_for(@post) do |f|
  = f.error_notification

  .form-inputs
    = f.input :user_id
    = f.input :content

  .form-actions
    = f.button :submit

app/views/posts/edit.html.slim
h1 Editing post

== render 'form'

= link_to 'Show', @post
'|
= link_to 'Back', posts_path

app/views/posts/index.html.slim
h1 Listing posts

table
  thead
    tr
      th User
      th Content
      th
      th
      th

  tbody
    - @posts.each do |post|
      tr
        td = post.user_id
        td = post.content
        td = link_to 'Show', post
        td = link_to 'Edit', edit_post_path(post)
        td = link_to 'Destroy', post, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Post', new_post_path

app/views/posts/new.html.slim
h1 New post

== render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.slim
.panel.panel-default
  .panel-body
    strong= "#{@post.user.full_name} : "
    = @post.content
  .panel-footer
    = link_to pluralize(@post.cached_votes_total, 'like'), like_post_path(@post), method: :post, class: 'btn btn-sm'
    = link_to pluralize(@post.comments_count, 'comment'), post_path(@post), class: 'btn btn-sm'

.panel.panel-primary
  .panel-heading Comments
  .panel-body
    = simple_form_for(@comment, url: post_comments_path(@post), method: :post) do |f|
      = f.input :comment, label: false, placeholder: 'Comment here...'
      = f.submit "Submit", class: 'btn btn-success'

  .list-group
    - @comments.each do |comment|
      a.list-group-item data-toggle="collapse" href="#comment_#{comment.id}"
        .comment
          strong= "#{comment.user.full_name} : "
          = comment.comment
        .created_at
          .pull-right
            small= comment.created_at.strftime("%B %d, %Y at %H:%M")
        .clearfix
      .collapse id="comment_#{comment.id}"
        .list-group-item
          = simple_form_for(@comment, url: comment_post_comment_path(@post, comment), method: :post) do |f|
            = f.input :comment, label: false, placeholder: 'Reply comment here...'
            = link_to pluralize(comment.cached_votes_total, 'like'), like_post_comment_path(@post, comment), method: :post, class: 'btn btn-default'
            |  
            = f.submit "Reply", class: 'btn btn-success'

          - unless comment.comments.empty?
            br
            .panel.panel-info
              .panel-heading Replies
              ul.list-group
                - comment.comments.each do |c|
                  li.list-group-item
                    strong= "#{c.user.full_name} : "
                    = c.comment
  .panel-footer
    = paginate @comments

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: 'btn btn-default' %>
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: 'btn btn-default' %>
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), class: 'btn btn-default' %>
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name), class: 'btn btn-default' %>
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name), class: 'btn btn-default' %>
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %>
  <% end -%>
<% end -%>